---
engines:
    duplication:
        enabled: true
        config:
            languages:
                javascript:
                    mass_threshold: 59

    eslint:
        enabled: true
        channel: eslint-3
    nodesecurity:
        enabled: false
    markdownlint:
        include_paths:
            - .md
        enabled: true
    fixme:
        enabled: true
ratings:
    paths:
        - src/**
exclude_paths:
    - ".nyc_output/"
    - docs/
    - core/
    - node_modules/
    - lib/
    - test/
    - testcoverage/
    - testingapp/
    - templates/
    - koaton
    - ".*"
    - "./**.json"
    - "./*.js"
